import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { Ajv, type AnySchema } from 'ajv';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { loadBundle, compile, hash } from './config.js';

// One approved bundle per execution mode: fake agents for synthetic fixtures,
// Grok agents for uploaded documents. Other workflow files stay validated by
// `pnpm config:validate` but cannot run. Runs snapshot the bundle they started with.
const approvedWorkflows = {
  synthetic: 'workflows/diligence.v1.json',
  live: 'workflows/investor-council.v1.json',
};
const modes = { 'local-fake-v1': 'synthetic', 'convex-grok-v1': 'live' };
const approved: Record<string, unknown> = {};
const schemas: Record<string, AnySchema> = {};
for (const [mode, file] of Object.entries(approvedWorkflows)) {
  const bundle = loadBundle('config', file);
  const { order, dependencies } = compile(bundle);
  if (modes[bundle.runnerVersion] !== mode)
    throw new Error(`${file} does not use the ${mode} runner`);
  approved[mode] = { bundle, configHash: hash(bundle), order, dependencies };
  for (const [id, schema] of Object.entries(bundle.schemas)) {
    if (schemas[id] && hash(schemas[id]) !== hash(schema))
      throw new Error(`Schema ${id} differs between bundles`);
    schemas[id] = schema;
  }
}

const ajv = new Ajv({
  strict: true,
  code: { source: true, esm: true },
  unicodeRegExp: false,
});
const ids = Object.keys(schemas).sort();
for (const id of ids) ajv.addSchema(schemas[id]!, id);
const names = Object.fromEntries(ids.map((id, i) => [`schema${i}`, id]));
const code = standaloneCode(ajv, names);
const generated = {
  'convex/analysis/approved.json':
    JSON.stringify(
      {
        ...approved,
        schemaNames: Object.fromEntries(
          Object.entries(names).map(([key, id]) => [id, key]),
        ),
      },
      null,
      2,
    ) + '\n',
  'convex/analysis/validators.js':
    '// Generated by pnpm config:generate. Do not edit.\n' + code + '\n',
  'convex/analysis/validators.d.ts':
    Object.keys(names)
      .map((key) => `export declare const ${key}: (value: unknown) => boolean;`)
      .join('\n') + '\n',
};
mkdirSync('convex/analysis', { recursive: true });
for (const [path, content] of Object.entries(generated)) {
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8') !== content)
      throw new Error(`Stale ${path}; run pnpm config:generate`);
  } else writeFileSync(path, content);
}
console.info(
  'Convex configuration snapshots and standalone schema validators are current.',
);
